Vagrant.configure("2") do |config|
    memory = "1024"
    cpus = 1
    config.vm.boot_timeout = 1200

    config.vm.box = "haiku-os/r1beta4-x86_64"
    config.vm.box_version = "20230114"

    # Disable vagrant vbguest auto update
    if Vagrant.has_plugin?("vagrant-vbguest") then
        config.vbguest.auto_update = false
    end

    config.vm.provider "virtualbox" do |vb|    
        # Display the VirtualBox GUI when booting the machine
        vb.gui = true
  
        # Customize the amount of memory on the VM:
        vb.memory = memory
        vb.cpus = cpus
    end

    # disable sync folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # prevent changing keys
    config.ssh.insert_key = false
end